image:
  file: .gitpod.Dockerfile

- name: MAIN - TERMINAL TO USE
  command: |
    clear
    echo "Welcome GRIT's curation tutorial"
    echo "typing './PretextView' will run PretextView - Remember to allow pop-ups!"
    echo "'ptt' is the alias for the pretext-to-tpf script!"
    echo " Run this for the tutorial: 'gp preview https://thebgacademy.org/BGA24/sessions/Genome-Curation'"
    echo "---- Have Fun ----"

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
